### ISSUE TITLE
Use of servo-freetype-sys seems to block using a Rust binding to freetype2 native library

### ISSUE THREAD

**Issue by johnoneil** [servo/libfreetype2#34]
Please excuse my questions.

I'm trying to resolve a build time conflict between (presumably) this crate and the `freetype-sys` crate. Both the `freetype-sys` and `servo-freetype-sys` crates link to the `freetype2` native library which is apparently not allowed by `cargo`.

I say this repo is "presumably" the one I'm interested in because the `crates.io` page for `servo-freetype-sys` points me here, despite the repo being differently named (it is named `libfreetype2`). To make it more confusing the `Cargo.toml` lists this crate as simply `freetype-sys`. I don't know what to make of any of that.

* question 1: Is this the repo for the `servo-freetype-sys` crate?

Now, assuming this is the repo I'm interested in, I can't make any sense of this as a crate as binding a native library. The `lib.rs` is blank.

* question 2: Is the purpose of this library simply to provide the `freetype2` native library and not to bind it to Rust code? Is this the reason the `lib.rs` is blank?

* Question 3: Am I wrong? Can this library be used from Rust code? If so how? If not, what is the purpose of a Rust crate that cannot be bound to Rust code?

Any answers are appreciated.

**Comment by mbrubeck** [comment]
> I say this repo is "presumably" the one I'm interested in because the `crates.io` page for `servo-freetype-sys` points me here, despite the repo being differently named (it is named `libfreetype2`).

Yeah, that's confusing.  It's named that way because this was originally a fork of the upstream `libfreetype2` project.

Many things about this crate are set up weirdly because it was created in the pre-Rust-1.0 days, before current conventions and best practices were established, and we never got around to modernizing it.

> To make it more confusing the `Cargo.toml` lists this crate as simply `freetype-sys`. I don't know what to make of any of that.

This package was previously named `freetype-sys`, but it was renamed because of the conflict with the other `freetype-sys` package. The `lib` name in Cargo.toml is still `freetype_sys`.

> * question 1: Is this the repo for the `servo-freetype-sys` crate?

Yes.

> * question 2: Is the purpose of this library simply to provide the `freetype2` native library and not to bind it to Rust code? Is this the reason the `lib.rs` is blank?

Yes, that's correct.  The purpose of this crate is to be used as a dependency by crates like `servo-skia` that link to other native libraries that depend on libfreetype2.  In other words, it doesn't provide anything useful to Rust code, but it builds and links Freetype for use by other C code.

**Comment by johnoneil** [comment]
@mbrubeck I appreciate your answers in these areas. Very helpful. I'm fairly new to both Rust and binding Rust with C but I can now clearly see how all this fits together. This info will be very helpful in my resolving my issue.

**Comment by mbrubeck** [comment]
Note: If possible, I think the ideal solution is to migrate away from this package, by updating all crates to use the [`freetype-sys`](https://crates.io/crates/freetype-sys) package instead.
